### ISSUE TITLE
Setting Up ESLint and Prettier Configurations

### ISSUE THREAD

**Issue by foss-cell-mec** [FossMec/fossmec-website-2023#1]
**Objective:**
The goal of this task is to set up ESLint and Prettier configurations for our project. These tools help maintain consistent code style and improve code readability.

**Tasks:**
1. **ESLint Configuration:**
   - Initialize ESLint in the project.
   - Configure ESLint rules based on best practices and project requirements.
   - Provide proper comments for ESLint rules for better understanding.

2. **Prettier Configuration:**
   - Initialize Prettier in the project.
   - Create a `.prettierrc` file with appropriate Prettier rules (e.g., indentation, semicolons, single quotes, etc.).
   - Integrate ESLint with Prettier using `eslint-config-prettier` and `eslint-plugin-prettier`.

**Resources:**
- ESLint Documentation: [ESLint Docs](https://eslint.org/docs/user-guide/getting-started)
- Prettier Documentation: [Prettier Docs](https://prettier.io/docs/en/index.html)
- `eslint-config-prettier` Documentation: [eslint-config-prettier](https://github.com/prettier/eslint-config-prettier)
- `eslint-plugin-prettier` Documentation: [eslint-plugin-prettier](https://github.com/prettier/eslint-plugin-prettier)

**Guidelines:**

### ESLint Configuration:

1. **React-Specific Rules:**
   - Use the recommended React ruleset: `"react"` and `"react-hooks"` plugins provide rules specifically designed for React development. You can extend from `"plugin:react/recommended"` in your ESLint configuration.
   ```json
   {
     "extends": ["eslint:recommended", "plugin:react/recommended"]
   }
   ```

2. **React Hooks:**
   - Enforce rules related to React Hooks usage. This ensures proper usage of useState, useEffect, useContext, etc.
   ```json
   {
     "plugins": ["react-hooks"],
     "rules": {
       "react-hooks/rules-of-hooks": "error",
       "react-hooks/exhaustive-deps": "warn"
     }
   }
   ```

3. **JSX and Formatting:**
   - Configure JSX-specific rules and formatting to ensure consistency in JSX code.
   ```json
   {
     "rules": {
       "react/jsx-uses-react": "error",
       "react/jsx-uses-vars": "error",
       "react/jsx-filename-extension": [1, { "extensions": [".js", ".jsx"] }],
       "react/jsx-indent": ["error", 2],
       "react/jsx-indent-props": ["error", 2]
     }
   }
   ```

### Prettier Configuration:

1. **Basic Formatting:**
   - Configure basic formatting rules, such as single quotes, trailing commas, and a maximum line length.
   ```json
   {
     "singleQuote": true,
     "trailingComma": "es5",
     "printWidth": 80,
     "tabWidth": 2
   }
   ```

2. **JSX Formatting:**
   - Customize formatting rules specific to JSX elements.
   ```json
   {
     "jsxSingleQuote": true,
     "jsxBracketSameLine": false
   }
   ```

**How to Contribute:**
1. Fork this repository.
2. Create a new branch: `git checkout -b eslint-prettier-setup`.
3. Work on the tasks mentioned above.
4. Commit your changes: `git commit -m "Add ESLint and Prettier configurations"`.
5. Push to the branch: `git push origin eslint-prettier-setup`.
6. Submit a pull request with a description of your changes.

**Comment by akssshh** [comment]
Can you assign this to me?

**Comment by foss-cell-mec** [comment]
Sure!
You may work on it.

**Comment by akssshh** [comment]
Thanks!!
