### ISSUE TITLE
Add a responsive about page based on design in the readme.

### ISSUE THREAD

**Issue by jzf21** [FossMec/fossmec-website-2023#15]

**Comment by JuanitaCathy** [comment]
hey! I'd like to work on this issue
can u assign it to me under the hacktoberfest label?

**Comment by Ayush-Bulbule** [comment]
Hello, I would like to work on this issue. I am skilled in frontend designing. Will you please assign this issue to me under hacktoberfest label?

**Comment by jzf21** [comment]
@JuanitaCathy you can work on this

**Comment by JuanitaCathy** [comment]
You just want the about us page as mentioned in the figma file right?

**Comment by JuanitaCathy** [comment]
> Yes. Should be responsive too.

I submitted a PR, please review. Thanks!
