### ISSUE TITLE
Logo and Hamburger menu is not responsive in small devices.

### ISSUE THREAD

**Issue by akssshh** [FossMec/fossmec-website-2023#3]
The logo and hamburger menu icon are not responsive on small devices, they appear side by side in the center of the screen.
![Screenshot 2023-10-01 at 12 40 17 PM](https://github.com/FossMec/fossmec-website-2023/assets/91525166/bb6afed0-9977-44b2-8d08-8c881df4b93d)

**Comment by akssshh** [comment]
Can someone assign this issue to me?

**Comment by akssshh** [comment]
Thanks!!

**Comment by 19dolly-hub** [comment]
May I try this sir...?

**Comment by Saurabhchaudhary9799** [comment]
hii sir ,i want to contribute on this  issue , please assign to me

**Comment by akssshh** [comment]
@foss-cell-mec i have made a PR!
