### ISSUE TITLE
Footer needs some improvement! 

### ISSUE THREAD

**Issue by akssshh** [FossMec/fossmec-website-2023#5]
<img width="807" alt="Screenshot 2023-10-01 at 7 30 54 PM" src="https://github.com/FossMec/fossmec-website-2023/assets/91525166/6c81ea1e-6e6d-4d6c-8aaa-eb32a2374ebb">

**Comment by akssshh** [comment]
Can someone assign this issue to me?

**Comment by blackchapel** [comment]
I would like to work on this. Will you please assign this issue to me
