### ISSUE TITLE
Change Navbar to followinf design

### ISSUE THREAD

**Issue by abhay-raj19** [FossMec/fossmec-website-2023#6]
will correct up the spacing b/w contact and scroll bar .
<img width="405" alt="image" src="https://github.com/FossMec/fossmec-website-2023/assets/96302417/27f60df7-0cc0-4dc6-b12b-230ad47bd17e">

will also enhance the UI of the Footer .
![image](https://github.com/FossMec/fossmec-website-2023/assets/96302417/9e284c20-bad8-40c8-80ff-4d06c5d4ddaf)

will design up the contact component with best UI.

I Will work on the  issue as soon as you assign me the issue .

**Comment by jzf21** [comment]
![image](https://github.com/FossMec/fossmec-website-2023/assets/67110139/4f25efff-ddab-4771-b66d-c8488a35cfab)
You can change the footer to make it look like this

**Comment by nnisarggada** [comment]
I'd like to work on this

**Comment by abhay-raj19** [comment]
sure @jzf21  i will make it like that .

thanks for assigning.

will raise up a PR as soon as possible.
