### ISSUE TITLE
Change Navbar to the following design

### ISSUE THREAD

**Issue by jzf21** [FossMec/fossmec-website-2023#8]
![image](https://github.com/FossMec/fossmec-website-2023/assets/67110139/4eaf6998-821b-469f-9314-a405e8a594b4)

Blue : #041424
Yellow:#F5A212

button styles:
border-radius: 3.125rem;
background: #F5A212;
box-shadow: 2px 4px 4px 1px #F9CD7F;

**Comment by HKABIG** [comment]
I think the navbar will require navlink routing using router-dom 
I would like to work on this 
can you please this  assign this to me

**Comment by jzf21** [comment]
It's a single page website so just link to the sections

**Comment by HKABIG** [comment]
Please check the pull Request

**Comment by jzf21** [comment]
Is it possible for you to make navbar responsive?

**Comment by HKABIG** [comment]
Ok I will do that
